x-nodered-base: &nodered-base
  image: nodered/node-red:3.1.10
  depends_on:
    - mosquitto
    - kafka
  restart: unless-stopped

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: presence_tracker_backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID}
      - KAFKA_TELEMETRY_TOPIC=${KAFKA_TELEMETRY_TOPIC}
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    depends_on:
      - postgres
      - kafka
      - influxdb
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    ports:
      - "1883:1883" # MQTT
      - "9001:9001" # WebSockets 
    volumes:
      - ./Mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=${KAFKA_NODE_ID}
      - KAFKA_PROCESS_ROLES=${KAFKA_PROCESS_ROLES}
      - KAFKA_CONTROLLER_QUORUM_VOTERS=${KAFKA_CONTROLLER_QUORUM_VOTERS}
      - KAFKA_LISTENERS=${KAFKA_LISTENERS}
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      - KAFKA_CONTROLLER_LISTENER_NAMES=${KAFKA_CONTROLLER_LISTENER_NAMES}
      - KAFKA_INTER_BROKER_LISTENER_NAME=${KAFKA_INTER_BROKER_LISTENER_NAME}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=${KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS}
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=${KAFKA_AUTO_CREATE_TOPICS_ENABLE}
      - KAFKA_NUM_PARTITIONS=${KAFKA_NUM_PARTITIONS}
      - KAFKA_LOG_RETENTION_HOURS=${KAFKA_LOG_RETENTION_HOURS}
      - KAFKA_LOG_DIRS=${KAFKA_LOG_DIRS}
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    restart: unless-stopped

  kafka-init:
    image: apache/kafka:3.7.0
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "-c"]
    command: >
      until /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list > /dev/null 2>&1;
      do echo "Waiting for Kafka..."; sleep 2; done;
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --create --if-not-exists --topic "$KAFKA_TELEMETRY_TOPIC" --partitions "$KAFKA_NUM_PARTITIONS" --replication-factor 1;
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --alter --topic "$KAFKA_TELEMETRY_TOPIC" --partitions "$KAFKA_NUM_PARTITIONS";
    environment:
      - KAFKA_TELEMETRY_TOPIC=${KAFKA_TELEMETRY_TOPIC}
      - KAFKA_NUM_PARTITIONS=${KAFKA_NUM_PARTITIONS}
    restart: "no"

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    env_file:
      - .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    restart: unless-stopped

  nodered-1:
    <<: *nodered-base
    container_name: nodered-1
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data

  nodered-2:
    <<: *nodered-base
    container_name: nodered-2
    volumes:
      - ./nodered/data-2:/data

  nodered-3:
    <<: *nodered-base
    container_name: nodered-3
    volumes:
      - ./nodered/data-3:/data