{
 "title": "Telegraf Docker Containers",
 "templating": {
  "list": [
   {
    "name": "container",
    "query": "label_values(docker_container_cpu_usage_percent, container_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{container_name=~\"$container\"}",
     "legendFormat": "{{container_name}} CPU"
    }
   ]
  },
  {
   "title": "Memory Usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "docker_container_mem_usage{container_name=~\"$container\"} / 1048576",
     "legendFormat": "{{container_name}} RAM"
    }
   ]
  },
  {
   "title": "Network Rx (MB/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(docker_container_net_rx_bytes{container_name=~\"$container\"}[1m]) / 1048576",
     "legendFormat": "{{container_name}} Net Rx"
    }
   ]
  },
  {
   "title": "Network Tx (MB/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(docker_container_net_tx_bytes{container_name=~\"$container\"}[1m]) / 1048576",
     "legendFormat": "{{container_name}} Net Tx"
    }
   ]
  },
  {
   "title": "Disk I/O Write Speed (MB/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(docker_container_blkio_io_service_bytes_recursive_write{container_name=~\"$container\"}[1m]) / 1048576",
     "legendFormat": "{{container_name}} Disk Write"
    }
   ]
  },
  {
   "title": "Disk I/O Read Speed (MB/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(docker_container_blkio_io_service_bytes_recursive_read{container_name=~\"$container\"}[1m]) / 1048576",
     "legendFormat": "{{container_name}} Disk Read"
    }
   ]
  }
 ]
}